/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appbiblioteca.c1_presentacion.form;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author
 * <AdvanceSoft - Osorio Perez Carlos Alfredo - advancesoft.trujillo@gmail.com>
 */
public class FormMenu extends javax.swing.JFrame {

    
    /*Para saber el ancho y el alto de cualquier pantalla*/
    int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
    int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        
    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        mostrarLookAndFeel();
        mostrarIcono();        
        initComponents();      
    }
    
    private void mostrarLookAndFeel() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    private void mostrarIcono() {        
        URL recurso = getClass().getResource("/appbiblioteca/c1_presentacion/iconos/bibliotecax64.png");
        Image icono = Toolkit.getDefaultToolkit().createImage(recurso);
        setIconImage(icono);
    } 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraArriba = new javax.swing.JToolBar();
        botonGestionarLibro = new javax.swing.JButton();
        botonGestionarLector = new javax.swing.JButton();
        botonGestionarProveedor = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        botonRegistrarPrestamo = new javax.swing.JButton();
        botonRegistrarDevolucion = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        botonSalir = new javax.swing.JButton();
        barraAbajo = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        etiquetaFondo = new javax.swing.JLabel();
        menuBiblioteca = new javax.swing.JMenuBar();
        menuGestionar = new javax.swing.JMenu();
        menuGestionarLibro = new javax.swing.JMenuItem();
        menuGestionarLector = new javax.swing.JMenuItem();
        menuGestionarBibliotecario = new javax.swing.JMenuItem();
        menuGestionarProveedor = new javax.swing.JMenuItem();
        menuGestionarNivel = new javax.swing.JMenuItem();
        menuGestionarEjemplar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuGestionarEspecilidad = new javax.swing.JMenuItem();
        menuGestionarAutor = new javax.swing.JMenuItem();
        menuGestionarUbicacion = new javax.swing.JMenu();
        menuGestionarUbicacionPiso = new javax.swing.JMenuItem();
        menuGestionarUbicacionArmario = new javax.swing.JMenuItem();
        menuGestionarUbicacionFila = new javax.swing.JMenuItem();
        menuProcesos = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuAutorReporte = new javax.swing.JMenu();
        menuListaAutores = new javax.swing.JMenuItem();
        menuLibroReporte = new javax.swing.JMenu();
        menuEspecialidadReporte = new javax.swing.JMenu();
        menuNivelReporte = new javax.swing.JMenu();
        menuBibliotecarioReporte = new javax.swing.JMenu();
        menuLectorReporte = new javax.swing.JMenu();
        menuProveedorReporte = new javax.swing.JMenu();
        menuPrestamoReporte = new javax.swing.JMenu();
        menuAdquisicionReporte = new javax.swing.JMenu();
        menuHerramientas = new javax.swing.JMenu();
        menuAplicacion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Software de Biblioteca - Quirihuac");
        setExtendedState(6);

        barraArriba.setRollover(true);

        botonGestionarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/librox64.png"))); // NOI18N
        botonGestionarLibro.setText("Libro");
        botonGestionarLibro.setFocusable(false);
        botonGestionarLibro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonGestionarLibro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonGestionarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarLibroActionPerformed(evt);
            }
        });
        barraArriba.add(botonGestionarLibro);

        botonGestionarLector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/lectorx64.png"))); // NOI18N
        botonGestionarLector.setText("Lector");
        botonGestionarLector.setFocusable(false);
        botonGestionarLector.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonGestionarLector.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonGestionarLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarLectorActionPerformed(evt);
            }
        });
        barraArriba.add(botonGestionarLector);

        botonGestionarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/proveedorx64.png"))); // NOI18N
        botonGestionarProveedor.setText("Proveedor");
        botonGestionarProveedor.setFocusable(false);
        botonGestionarProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonGestionarProveedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonGestionarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarProveedorActionPerformed(evt);
            }
        });
        barraArriba.add(botonGestionarProveedor);
        barraArriba.add(jSeparator2);

        botonRegistrarPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/prestamox64.png"))); // NOI18N
        botonRegistrarPrestamo.setText("Prestamo");
        botonRegistrarPrestamo.setFocusable(false);
        botonRegistrarPrestamo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRegistrarPrestamo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonRegistrarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarPrestamoActionPerformed(evt);
            }
        });
        barraArriba.add(botonRegistrarPrestamo);

        botonRegistrarDevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/prestamodevolucionx64.png"))); // NOI18N
        botonRegistrarDevolucion.setText("Devolución");
        botonRegistrarDevolucion.setFocusable(false);
        botonRegistrarDevolucion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRegistrarDevolucion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonRegistrarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarDevolucionActionPerformed(evt);
            }
        });
        barraArriba.add(botonRegistrarDevolucion);
        barraArriba.add(jSeparator3);

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/salirmenux64.png"))); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.setFocusable(false);
        botonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        barraArriba.add(botonSalir);

        getContentPane().add(barraArriba, java.awt.BorderLayout.PAGE_START);

        barraAbajo.setFloatable(false);
        barraAbajo.setRollover(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Bibliotecario(a):");
        barraAbajo.add(jLabel2);

        jLabel1.setText("Nombre del bibliotecario");
        barraAbajo.add(jLabel1);

        getContentPane().add(barraAbajo, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(etiquetaFondo, java.awt.BorderLayout.CENTER);

        menuGestionar.setText("Gestionar");

        menuGestionarLibro.setBackground(new java.awt.Color(255, 255, 255));
        menuGestionarLibro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuGestionarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/librox32.png"))); // NOI18N
        menuGestionarLibro.setText("Gestionar Libro");
        menuGestionarLibro.setOpaque(true);
        menuGestionarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarLibroActionPerformed(evt);
            }
        });
        menuGestionar.add(menuGestionarLibro);

        menuGestionarLector.setBackground(new java.awt.Color(255, 255, 255));
        menuGestionarLector.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuGestionarLector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/lectorx32.png"))); // NOI18N
        menuGestionarLector.setText("Gestionar Lector");
        menuGestionarLector.setOpaque(true);
        menuGestionarLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarLectorActionPerformed(evt);
            }
        });
        menuGestionar.add(menuGestionarLector);

        menuGestionarBibliotecario.setBackground(new java.awt.Color(255, 255, 255));
        menuGestionarBibliotecario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuGestionarBibliotecario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/bibliotecariox32.png"))); // NOI18N
        menuGestionarBibliotecario.setText("Gestionar Bibliotecario");
        menuGestionarBibliotecario.setOpaque(true);
        menuGestionarBibliotecario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarBibliotecarioActionPerformed(evt);
            }
        });
        menuGestionar.add(menuGestionarBibliotecario);

        menuGestionarProveedor.setBackground(new java.awt.Color(255, 255, 255));
        menuGestionarProveedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuGestionarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/proveedorx32.png"))); // NOI18N
        menuGestionarProveedor.setText("Gestionar Proveedor");
        menuGestionarProveedor.setOpaque(true);
        menuGestionarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarProveedorActionPerformed(evt);
            }
        });
        menuGestionar.add(menuGestionarProveedor);

        menuGestionarNivel.setBackground(new java.awt.Color(255, 255, 255));
        menuGestionarNivel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuGestionarNivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/nivelx32.png"))); // NOI18N
        menuGestionarNivel.setText("Gestionar Nivel");
        menuGestionarNivel.setOpaque(true);
        menuGestionarNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarNivelActionPerformed(evt);
            }
        });
        menuGestionar.add(menuGestionarNivel);

        menuGestionarEjemplar.setBackground(new java.awt.Color(255, 255, 255));
        menuGestionarEjemplar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuGestionarEjemplar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/ejemplarx32.png"))); // NOI18N
        menuGestionarEjemplar.setText("Gestionar Ejemplar");
        menuGestionarEjemplar.setOpaque(true);
        menuGestionarEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarEjemplarActionPerformed(evt);
            }
        });
        menuGestionar.add(menuGestionarEjemplar);
        menuGestionar.add(jSeparator1);

        menuGestionarEspecilidad.setBackground(new java.awt.Color(255, 255, 255));
        menuGestionarEspecilidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuGestionarEspecilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/especialidadx32.png"))); // NOI18N
        menuGestionarEspecilidad.setText("Gestionar Especilidad");
        menuGestionarEspecilidad.setOpaque(true);
        menuGestionarEspecilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarEspecilidadActionPerformed(evt);
            }
        });
        menuGestionar.add(menuGestionarEspecilidad);

        menuGestionarAutor.setBackground(new java.awt.Color(255, 255, 255));
        menuGestionarAutor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuGestionarAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/autorx32.png"))); // NOI18N
        menuGestionarAutor.setText("Gestionar Autor");
        menuGestionarAutor.setOpaque(true);
        menuGestionarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarAutorActionPerformed(evt);
            }
        });
        menuGestionar.add(menuGestionarAutor);

        menuGestionarUbicacion.setBackground(new java.awt.Color(255, 255, 255));
        menuGestionarUbicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/ubicacionx32.png"))); // NOI18N
        menuGestionarUbicacion.setText("Gestionar Ubicacion");
        menuGestionarUbicacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuGestionarUbicacion.setOpaque(true);

        menuGestionarUbicacionPiso.setBackground(new java.awt.Color(255, 255, 255));
        menuGestionarUbicacionPiso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuGestionarUbicacionPiso.setText("Ubicacion Piso");
        menuGestionarUbicacionPiso.setOpaque(true);
        menuGestionarUbicacionPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarUbicacionPisoActionPerformed(evt);
            }
        });
        menuGestionarUbicacion.add(menuGestionarUbicacionPiso);

        menuGestionarUbicacionArmario.setBackground(new java.awt.Color(255, 255, 255));
        menuGestionarUbicacionArmario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuGestionarUbicacionArmario.setText("Ubicacion Armario");
        menuGestionarUbicacionArmario.setOpaque(true);
        menuGestionarUbicacionArmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarUbicacionArmarioActionPerformed(evt);
            }
        });
        menuGestionarUbicacion.add(menuGestionarUbicacionArmario);

        menuGestionarUbicacionFila.setBackground(new java.awt.Color(255, 255, 255));
        menuGestionarUbicacionFila.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuGestionarUbicacionFila.setText("Ubicacion Fila");
        menuGestionarUbicacionFila.setOpaque(true);
        menuGestionarUbicacionFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarUbicacionFilaActionPerformed(evt);
            }
        });
        menuGestionarUbicacion.add(menuGestionarUbicacionFila);

        menuGestionar.add(menuGestionarUbicacion);

        menuBiblioteca.add(menuGestionar);

        menuProcesos.setText("Procesos");

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/almacenx32.png"))); // NOI18N
        jMenu1.setText("Almacen");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu1.setOpaque(true);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/adquisicionx32.png"))); // NOI18N
        jMenuItem1.setText("Adquisición de Libros");
        jMenuItem1.setOpaque(true);
        jMenu1.add(jMenuItem1);

        menuProcesos.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/atencionx32.png"))); // NOI18N
        jMenu2.setText("Atención");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu2.setOpaque(true);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/prestamox32.png"))); // NOI18N
        jMenuItem2.setText("Prestamo");
        jMenuItem2.setOpaque(true);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/prestamodevolucionx32.png"))); // NOI18N
        jMenuItem3.setText("Devolución");
        jMenuItem3.setOpaque(true);
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        menuProcesos.add(jMenu2);

        menuBiblioteca.add(menuProcesos);

        menuReportes.setText("Reportes");

        menuAutorReporte.setBackground(new java.awt.Color(255, 255, 255));
        menuAutorReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/reportegeneralx32.png"))); // NOI18N
        menuAutorReporte.setText("Autor");
        menuAutorReporte.setOpaque(true);

        menuListaAutores.setText("Lista de Autores");
        menuAutorReporte.add(menuListaAutores);

        menuReportes.add(menuAutorReporte);

        menuLibroReporte.setBackground(new java.awt.Color(255, 255, 255));
        menuLibroReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/reportegeneralx32.png"))); // NOI18N
        menuLibroReporte.setText("Libro");
        menuLibroReporte.setOpaque(true);
        menuReportes.add(menuLibroReporte);

        menuEspecialidadReporte.setBackground(new java.awt.Color(255, 255, 255));
        menuEspecialidadReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/reportegeneralx32.png"))); // NOI18N
        menuEspecialidadReporte.setText("Especialidad");
        menuEspecialidadReporte.setOpaque(true);
        menuReportes.add(menuEspecialidadReporte);

        menuNivelReporte.setBackground(new java.awt.Color(255, 255, 255));
        menuNivelReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/reportegeneralx32.png"))); // NOI18N
        menuNivelReporte.setText("Nivel");
        menuNivelReporte.setOpaque(true);
        menuReportes.add(menuNivelReporte);

        menuBibliotecarioReporte.setBackground(new java.awt.Color(255, 255, 255));
        menuBibliotecarioReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/reportegeneralx32.png"))); // NOI18N
        menuBibliotecarioReporte.setText("Bibliotecario");
        menuBibliotecarioReporte.setOpaque(true);
        menuReportes.add(menuBibliotecarioReporte);

        menuLectorReporte.setBackground(new java.awt.Color(255, 255, 255));
        menuLectorReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/reportegeneralx32.png"))); // NOI18N
        menuLectorReporte.setText("Lector");
        menuLectorReporte.setOpaque(true);
        menuReportes.add(menuLectorReporte);

        menuProveedorReporte.setBackground(new java.awt.Color(255, 255, 255));
        menuProveedorReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/reportegeneralx32.png"))); // NOI18N
        menuProveedorReporte.setText("Proveedor");
        menuProveedorReporte.setOpaque(true);
        menuReportes.add(menuProveedorReporte);

        menuPrestamoReporte.setBackground(new java.awt.Color(255, 255, 255));
        menuPrestamoReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/reportegeneralx32.png"))); // NOI18N
        menuPrestamoReporte.setText("Prestamo");
        menuPrestamoReporte.setOpaque(true);
        menuReportes.add(menuPrestamoReporte);

        menuAdquisicionReporte.setBackground(new java.awt.Color(255, 255, 255));
        menuAdquisicionReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbiblioteca/c1_presentacion/iconos/reportegeneralx32.png"))); // NOI18N
        menuAdquisicionReporte.setText("Adquisicion");
        menuAdquisicionReporte.setOpaque(true);
        menuReportes.add(menuAdquisicionReporte);

        menuBiblioteca.add(menuReportes);

        menuHerramientas.setText("Herramientas");
        menuBiblioteca.add(menuHerramientas);

        menuAplicacion.setText("Aplicacion");
        menuBiblioteca.add(menuAplicacion);

        setJMenuBar(menuBiblioteca);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void menuGestionarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarProveedorActionPerformed
        // TODO add your handling code here:
        FormGestionarProveedor formGestionarProveedor = new FormGestionarProveedor(this);
        formGestionarProveedor.setVisible(true);
    }//GEN-LAST:event_menuGestionarProveedorActionPerformed

    private void botonGestionarLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarLectorActionPerformed
        // TODO add your handling code here:
        FormGestionarLector formGestionarLector = new FormGestionarLector(this);
        formGestionarLector.setVisible(true);
    }//GEN-LAST:event_botonGestionarLectorActionPerformed

    private void botonGestionarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarProveedorActionPerformed
        // TODO add your handling code here:
        FormGestionarProveedor formGestionarProveedor = new FormGestionarProveedor(this);
        formGestionarProveedor.setVisible(true);    
    }//GEN-LAST:event_botonGestionarProveedorActionPerformed

    private void menuGestionarEspecilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarEspecilidadActionPerformed
        // TODO add your handling code here:
        FormGestionarEspecialidad formGestionarEspecialidad = new FormGestionarEspecialidad(this);
        formGestionarEspecialidad.setVisible(true);
    }//GEN-LAST:event_menuGestionarEspecilidadActionPerformed

    private void menuGestionarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarAutorActionPerformed
        // TODO add your handling code here:
        FormGestionarAutor formGestionarAutor = new FormGestionarAutor(this);
        formGestionarAutor.setVisible(true);
    }//GEN-LAST:event_menuGestionarAutorActionPerformed

    private void menuGestionarUbicacionPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarUbicacionPisoActionPerformed
        // TODO add your handling code here:
        FormGestionarUbicacionPiso formGestionarUbicacionPiso = new FormGestionarUbicacionPiso(this);
        formGestionarUbicacionPiso.setVisible(true);
    }//GEN-LAST:event_menuGestionarUbicacionPisoActionPerformed

    private void menuGestionarUbicacionFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarUbicacionFilaActionPerformed
        // TODO add your handling code here:
        FormGestionarUbicacionFila formGestionarUbicacionFila = new FormGestionarUbicacionFila(this);
        formGestionarUbicacionFila.setVisible(true);
    }//GEN-LAST:event_menuGestionarUbicacionFilaActionPerformed

    private void menuGestionarUbicacionArmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarUbicacionArmarioActionPerformed
        // TODO add your handling code here:
        FormGestionarUbicacionArmario formGestionarUbicacionArmario = new FormGestionarUbicacionArmario(this);
        formGestionarUbicacionArmario.setVisible(true);
    }//GEN-LAST:event_menuGestionarUbicacionArmarioActionPerformed

    private void menuGestionarEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarEjemplarActionPerformed
        FormGestionarEjemplar formGestionarEjemplar = new FormGestionarEjemplar(this);
        formGestionarEjemplar.setVisible(true);
    }//GEN-LAST:event_menuGestionarEjemplarActionPerformed

    private void menuGestionarBibliotecarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarBibliotecarioActionPerformed
        // TODO add your handling code here:
        new FormGestionarBibliotecario(this).setVisible(true);
    }//GEN-LAST:event_menuGestionarBibliotecarioActionPerformed

    private void menuGestionarLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarLectorActionPerformed
        // TODO add your handling code here:
        new FormGestionarLector(this).setVisible(true);
    }//GEN-LAST:event_menuGestionarLectorActionPerformed

    private void menuGestionarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarLibroActionPerformed
        // TODO add your handling code here:
        FormGestionarLibro formGestionarLibro = new FormGestionarLibro(this);
        formGestionarLibro.setVisible(true); 
    }//GEN-LAST:event_menuGestionarLibroActionPerformed

    private void menuGestionarNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarNivelActionPerformed
        // TODO add your handling code here:
        FormGestionarNivel formGestionarNivel = new FormGestionarNivel(this);
        formGestionarNivel.setVisible(true);
    }//GEN-LAST:event_menuGestionarNivelActionPerformed

    private void botonGestionarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarLibroActionPerformed
        // TODO add your handling code here:
        FormGestionarLibro formGestionarLibro = new FormGestionarLibro(this);
        formGestionarLibro.setVisible(true);
    }//GEN-LAST:event_botonGestionarLibroActionPerformed

    private void botonRegistrarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarPrestamoActionPerformed
        // TODO add your handling code here:
        FormRegistrarPrestamo formRegistrarPrestamo = new FormRegistrarPrestamo(this);
        formRegistrarPrestamo.setVisible(true);
    }//GEN-LAST:event_botonRegistrarPrestamoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FormRegistrarPrestamo formRegistrarPrestamo = new FormRegistrarPrestamo(this);
        formRegistrarPrestamo.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void botonRegistrarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarDevolucionActionPerformed
        // TODO add your handling code here:
        FormRegistrarDevolucion formRegistrarDevolucion = new FormRegistrarDevolucion(this);
        formRegistrarDevolucion.setVisible(true);
    }//GEN-LAST:event_botonRegistrarDevolucionActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        FormRegistrarDevolucion formRegistrarDevolucion = new FormRegistrarDevolucion(this);
        formRegistrarDevolucion.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraAbajo;
    private javax.swing.JToolBar barraArriba;
    private javax.swing.JButton botonGestionarLector;
    private javax.swing.JButton botonGestionarLibro;
    private javax.swing.JButton botonGestionarProveedor;
    private javax.swing.JButton botonRegistrarDevolucion;
    private javax.swing.JButton botonRegistrarPrestamo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel etiquetaFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JMenu menuAdquisicionReporte;
    private javax.swing.JMenu menuAplicacion;
    private javax.swing.JMenu menuAutorReporte;
    private javax.swing.JMenuBar menuBiblioteca;
    private javax.swing.JMenu menuBibliotecarioReporte;
    private javax.swing.JMenu menuEspecialidadReporte;
    private javax.swing.JMenu menuGestionar;
    private javax.swing.JMenuItem menuGestionarAutor;
    private javax.swing.JMenuItem menuGestionarBibliotecario;
    private javax.swing.JMenuItem menuGestionarEjemplar;
    private javax.swing.JMenuItem menuGestionarEspecilidad;
    private javax.swing.JMenuItem menuGestionarLector;
    private javax.swing.JMenuItem menuGestionarLibro;
    private javax.swing.JMenuItem menuGestionarNivel;
    private javax.swing.JMenuItem menuGestionarProveedor;
    private javax.swing.JMenu menuGestionarUbicacion;
    private javax.swing.JMenuItem menuGestionarUbicacionArmario;
    private javax.swing.JMenuItem menuGestionarUbicacionFila;
    private javax.swing.JMenuItem menuGestionarUbicacionPiso;
    private javax.swing.JMenu menuHerramientas;
    private javax.swing.JMenu menuLectorReporte;
    private javax.swing.JMenu menuLibroReporte;
    private javax.swing.JMenuItem menuListaAutores;
    private javax.swing.JMenu menuNivelReporte;
    private javax.swing.JMenu menuPrestamoReporte;
    private javax.swing.JMenu menuProcesos;
    private javax.swing.JMenu menuProveedorReporte;
    private javax.swing.JMenu menuReportes;
    // End of variables declaration//GEN-END:variables
}
